### ISSUE TITLE
Error with vega-lite 2.1

### ISSUE THREAD

**Issue by eibanez** [vega/vega-tooltip#145]
I just updated to the newly released vega-lite 2.1 and I am getting the following error:

```
Uncaught (in promise) TypeError: vl.fieldDef.field is not a function
    at supplementFieldOption
```

As far as I can tell the error happens at the last line of this snippet. This worked fine in 2.0.4.

Thanks for the help!

```
function supplementFieldOption(fieldOption, fieldDef, vlSpec) {
    // many specs don't have config
    var config = __assign({}, vlSpec.config);
    // at least one of fieldOption and fieldDef should exist
    if (!fieldOption && !fieldDef) {
        console.error('[Tooltip] Cannot supplement a field when field and fieldDef are both empty.');
        return undefined;
    }
    // if either one of fieldOption and fieldDef is undefined, make it an empty object
    if (!fieldOption && fieldDef) {
        fieldOption = {};
    }
    if (fieldOption && !fieldDef) {
        fieldDef = {};
    }
    // the supplemented field option
    var supplementedFieldOption = {};
    // supplement a user-provided field name with underscore prefixes and suffixes to
    // match the field names in item.datum
    // for aggregation, this will add prefix "mean_" etc.
    // for timeUnit, this will add prefix "yearmonth_" etc.
    // for bin, this will add prefix "bin_" and suffix "_start". Later we will replace "_start" with "_range".
    supplementedFieldOption.field = fieldDef.field ?
        vl.fieldDef.field(fieldDef) : fieldOption.field;
...
```

**Comment by domoritz** [comment]
The function is now called vlField. We will update vega tooltip.

**Comment by domoritz** [comment]
In fact, it's already fixed in master: https://github.com/vega/vega-tooltip/commit/162d1dc5f4a20538bef4b7a623ceadb7e38eb872

**Comment by eibanez** [comment]
Great, thanks!
<https://github.com/vega/vega-tooltip/commit/162d1dc5f4a20538bef4b7a623ceadb7e38eb872>

**Comment by domoritz** [comment]
0.5 released
